version: '3.8'

services:
  cadastro-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cadastro-girabot
    restart: unless-stopped
    ports:
      - "3001:80"
    environment:
      - NODE_ENV=production
    networks:
      - girabot-network
    labels:
      - "com.girabot.description=Sistema de Cadastro de Franqueados"
      - "com.girabot.version=1.0.0"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  girabot-network:
    driver: bridge
